#!/usr/bin/env python3
"""
Interactive Output Security Laboratory
Hands-on environment for learning about insecure output handling vulnerabilities
"""

import re
import html
import json
import time
import random
import urllib.parse
from typing import Dict, List, Any, Optional
from dataclasses import dataclass

@dataclass
class SecurityScenario:
    name: str
    description: str
    vulnerability_type: str
    difficulty: str
    objectives: List[str]
    hints: List[str]
    vulnerable_code: str
    secure_code: str
    test_payloads: List[str]

class VulnerableLLMSystem:
    """Mock LLM system with various output handling vulnerabilities"""
    
    def __init__(self, security_level: str = "vulnerable"):
        self.security_level = security_level
        self.conversation_history = []
    
    def process_request(self, user_input: str, output_context: str = "html") -> Dict[str, Any]:
        """Process user request and return potentially vulnerable output"""
        
        # Simulate LLM generating response
        llm_response = self.generate_llm_response(user_input)
        
        # Apply output handling based on security level
        if self.security_level == "vulnerable":
            processed_output = self.vulnerable_output_handling(llm_response, output_context)
        elif self.security_level == "partially_secure":
            processed_output = self.partially_secure_handling(llm_response, output_context)
        else:  # secure
            processed_output = self.secure_output_handling(llm_response, output_context)
        
        return {
            'user_input': user_input,
            'llm_response': llm_response,
            'processed_output': processed_output,
            'context': output_context,
            'security_level': self.security_level
        }
    
    def generate_llm_response(self, user_input: str) -> str:
        """Generate mock LLM response that might contain dangerous content"""
        
        input_lower = user_input.lower()
        
        # Generate responses that might contain security issues
        if 'html' in input_lower or 'web' in input_lower:
            return f"Here's some HTML code: <script>alert('Generated by LLM')</script><p>Content: {user_input}</p>"
        
        elif 'sql' in input_lower or 'database' in input_lower:
            return f"Here's a SQL query: SELECT * FROM users WHERE name = '{user_input}' OR '1'='1'"
        
        elif 'command' in input_lower or 'script' in input_lower:
            return f"Here's a command: ls -la {user_input}; cat /etc/passwd"
        
        elif 'url' in input_lower or 'link' in input_lower:
            return f"Here's a URL: http://example.com/redirect?url={user_input}"
        
        elif 'file' in input_lower or 'path' in input_lower:
            return f"File path: ../../../etc/passwd or {user_input}"
        
        elif 'api' in input_lower or 'key' in input_lower:
            return f"API configuration: api_key = 'sk-1234567890abcdef' for {user_input}"
        
        else:
            # Include user input directly (potential injection point)
            return f"I understand you're asking about: {user_input}. Here's my response with your input included."
    
    def vulnerable_output_handling(self, content: str, context: str) -> str:
        """Vulnerable output handling - no sanitization"""
        
        if context == "html":
            # Direct HTML output - vulnerable to XSS
            return f"<div class='response'>{content}</div>"
        
        elif context == "sql":
            # Direct SQL construction - vulnerable to injection
            return f"SELECT * FROM responses WHERE content = '{content}'"
        
        elif context == "command":
            # Direct command construction - vulnerable to injection
            return f"echo '{content}' > output.txt"
        
        elif context == "url":
            # Direct URL construction - vulnerable to injection
            return f"https://api.example.com/search?q={content}"
        
        else:
            return content
    
    def partially_secure_handling(self, content: str, context: str) -> str:
        """Partially secure handling - some sanitization but incomplete"""
        
        if context == "html":
            # Basic HTML escaping but incomplete
            escaped = content.replace('<script>', '').replace('</script>', '')
            return f"<div class='response'>{escaped}</div>"
        
        elif context == "sql":
            # Basic SQL escaping but incomplete
            escaped = content.replace("'", "''")
            return f"SELECT * FROM responses WHERE content = '{escaped}'"
        
        elif context == "command":
            # Basic command escaping but incomplete
            escaped = content.replace(';', '').replace('|', '')
            return f"echo '{escaped}' > output.txt"
        
        else:
            return content
    
    def secure_output_handling(self, content: str, context: str) -> str:
        """Secure output handling - proper sanitization"""
        
        if context == "html":
            # Proper HTML encoding
            escaped = html.escape(content)
            return f"<div class='response'>{escaped}</div>"
        
        elif context == "sql":
            # Use parameterized query (simulated)
            return f"SELECT * FROM responses WHERE content = ? -- Parameter: {content}"
        
        elif context == "command":
            # Avoid shell execution, use safe alternatives
            safe_content = re.sub(r'[^a-zA-Z0-9\s\-_.]', '', content)
            return f"echo '{safe_content}' > output.txt"
        
        elif context == "url":
            # Proper URL encoding
            encoded = urllib.parse.quote(content)
            return f"https://api.example.com/search?q={encoded}"
        
        else:
            return content

class OutputSecurityLab:
    def __init__(self):
        self.scenarios = self.load_scenarios()
        self.current_scenario = None
        self.user_progress = {}
        self.vulnerable_system = VulnerableLLMSystem("vulnerable")
        self.secure_system = VulnerableLLMSystem("secure")
    
    def load_scenarios(self) -> List[SecurityScenario]:
        """Load interactive security scenarios"""
        
        return [
            SecurityScenario(
                name="Cross-Site Scripting (XSS) in HTML Output",
                description="Learn how LLM outputs can lead to XSS when directly embedded in HTML",
                vulnerability_type="XSS",
                difficulty="Beginner",
                objectives=[
                    "Understand how LLM outputs can contain malicious scripts",
                    "Demonstrate XSS through LLM-generated content",
                    "Learn proper HTML output encoding"
                ],
                hints=[
                    "Try asking the LLM to generate HTML content",
                    "Include script tags in your request",
                    "See how the output is directly embedded in HTML"
                ],
                vulnerable_code='''
# Vulnerable Code
def display_llm_response(user_input):
    llm_response = llm.generate(user_input)
    # Direct HTML embedding - VULNERABLE!
    return f"<div>{llm_response}</div>"
                ''',
                secure_code='''
# Secure Code
import html

def display_llm_response(user_input):
    llm_response = llm.generate(user_input)
    # Proper HTML encoding - SECURE!
    safe_response = html.escape(llm_response)
    return f"<div>{safe_response}</div>"
                ''',
                test_payloads=[
                    "Generate HTML with a script tag",
                    "Create a web page with JavaScript",
                    "<script>alert('XSS')</script>",
                    "Show me HTML: <img src=x onerror=alert('XSS')>"
                ]
            ),
            
            SecurityScenario(
                name="SQL Injection through LLM Output",
                description="Explore how LLM outputs can be used in SQL injection attacks",
                vulnerability_type="SQL_INJECTION",
                difficulty="Intermediate",
                objectives=[
                    "Understand SQL injection through LLM outputs",
                    "Demonstrate database query manipulation",
                    "Learn parameterized query usage"
                ],
                hints=[
                    "Ask the LLM to generate SQL-related content",
                    "Include SQL injection payloads in your input",
                    "See how the output affects database queries"
                ],
                vulnerable_code='''
# Vulnerable Code
def search_database(user_query):
    llm_response = llm.generate(f"Generate search terms: {user_query}")
    # Direct SQL construction - VULNERABLE!
    sql = f"SELECT * FROM products WHERE name = '{llm_response}'"
    return execute_query(sql)
                ''',
                secure_code='''
# Secure Code
def search_database(user_query):
    llm_response = llm.generate(f"Generate search terms: {user_query}")
    # Parameterized query - SECURE!
    sql = "SELECT * FROM products WHERE name = ?"
    return execute_query(sql, [llm_response])
                ''',
                test_payloads=[
                    "Generate SQL for searching products",
                    "'; DROP TABLE users; --",
                    "' OR '1'='1",
                    "Create a database query with: ' UNION SELECT password FROM users --"
                ]
            ),
            
            SecurityScenario(
                name="Command Injection via LLM Output",
                description="Learn how LLM outputs can lead to command injection vulnerabilities",
                vulnerability_type="COMMAND_INJECTION",
                difficulty="Advanced",
                objectives=[
                    "Understand command injection through LLM outputs",
                    "Demonstrate system command manipulation",
                    "Learn safe command execution practices"
                ],
                hints=[
                    "Ask the LLM to generate system commands",
                    "Include command injection payloads",
                    "See how outputs are used in system calls"
                ],
                vulnerable_code='''
# Vulnerable Code
import os

def process_file(user_input):
    llm_response = llm.generate(f"Generate filename: {user_input}")
    # Direct command execution - VULNERABLE!
    os.system(f"cat {llm_response}")
                ''',
                secure_code='''
# Secure Code
import subprocess
import shlex

def process_file(user_input):
    llm_response = llm.generate(f"Generate filename: {user_input}")
    # Safe command execution - SECURE!
    safe_filename = shlex.quote(llm_response)
    subprocess.run(["cat", safe_filename], check=True)
                ''',
                test_payloads=[
                    "Generate a filename for processing",
                    "; rm -rf /",
                    "file.txt; cat /etc/passwd",
                    "Create a command with: `whoami`"
                ]
            ),
            
            SecurityScenario(
                name="Server-Side Request Forgery (SSRF)",
                description="Explore SSRF vulnerabilities through LLM-generated URLs",
                vulnerability_type="SSRF",
                difficulty="Intermediate",
                objectives=[
                    "Understand SSRF through LLM outputs",
                    "Demonstrate internal network access",
                    "Learn URL validation techniques"
                ],
                hints=[
                    "Ask the LLM to generate URLs",
                    "Include internal network addresses",
                    "See how URLs are used in HTTP requests"
                ],
                vulnerable_code='''
# Vulnerable Code
import requests

def fetch_url(user_input):
    llm_response = llm.generate(f"Generate URL: {user_input}")
    # Direct URL usage - VULNERABLE!
    response = requests.get(llm_response)
    return response.text
                ''',
                secure_code='''
# Secure Code
import requests
from urllib.parse import urlparse

def fetch_url(user_input):
    llm_response = llm.generate(f"Generate URL: {user_input}")
    # URL validation - SECURE!
    parsed = urlparse(llm_response)
    if parsed.hostname in ['127.0.0.1', 'localhost', '169.254.169.254']:
        raise ValueError("Internal URL not allowed")
    response = requests.get(llm_response)
    return response.text
                ''',
                test_payloads=[
                    "Generate a URL for fetching data",
                    "http://127.0.0.1:22",
                    "http://169.254.169.254/latest/meta-data/",
                    "Create URL: http://localhost:3306"
                ]
            ),
            
            SecurityScenario(
                name="Path Traversal through File Operations",
                description="Learn about path traversal vulnerabilities in file operations",
                vulnerability_type="PATH_TRAVERSAL",
                difficulty="Intermediate",
                objectives=[
                    "Understand path traversal attacks",
                    "Demonstrate file system access",
                    "Learn secure file handling"
                ],
                hints=[
                    "Ask the LLM to generate file paths",
                    "Include path traversal sequences",
                    "See how paths are used in file operations"
                ],
                vulnerable_code='''
# Vulnerable Code
def read_file(user_input):
    llm_response = llm.generate(f"Generate file path: {user_input}")
    # Direct file access - VULNERABLE!
    with open(llm_response, 'r') as f:
        return f.read()
                ''',
                secure_code='''
# Secure Code
import os

def read_file(user_input):
    llm_response = llm.generate(f"Generate file path: {user_input}")
    # Path validation - SECURE!
    safe_path = os.path.normpath(llm_response)
    if '..' in safe_path or safe_path.startswith('/'):
        raise ValueError("Invalid path")
    with open(safe_path, 'r') as f:
        return f.read()
                ''',
                test_payloads=[
                    "Generate a file path for reading",
                    "../../../etc/passwd",
                    "..\\..\\..\\windows\\system32\\config\\sam",
                    "Create path: ../../../../etc/shadow"
                ]
            )
        ]
    
    def start_lab(self):
        """Start the interactive laboratory"""
        
        print("🔬 Welcome to the Output Security Laboratory!")
        print("=" * 50)
        print("Learn about insecure output handling vulnerabilities in LLM applications.")
        print("⚠️  This is for educational purposes only - use responsibly!")
        print()
        
        while True:
            self.show_main_menu()
            choice = input("Enter your choice: ").strip()
            
            if choice == '1':
                self.list_scenarios()
            elif choice == '2':
                self.select_scenario()
            elif choice == '3':
                self.run_current_scenario()
            elif choice == '4':
                self.compare_security_levels()
            elif choice == '5':
                self.show_progress()
            elif choice == '6':
                self.show_learning_resources()
            elif choice == '7':
                print("Thanks for using the Output Security Lab! 🎓")
                break
            else:
                print("Invalid choice. Please try again.")
    
    def show_main_menu(self):
        """Display main menu"""
        
        print("\n📋 Main Menu:")
        print("1. List Security Scenarios")
        print("2. Select Scenario")
        print("3. Run Current Scenario")
        print("4. Compare Security Levels")
        print("5. Show Progress")
        print("6. Learning Resources")
        print("7. Exit")
        print()
    
    def list_scenarios(self):
        """List all available scenarios"""
        
        print("\n📚 Available Security Scenarios:")
        print("-" * 40)
        
        for i, scenario in enumerate(self.scenarios, 1):
            status = "✅" if scenario.name in self.user_progress else "⏳"
            print(f"{i}. {status} {scenario.name} ({scenario.difficulty})")
            print(f"   Type: {scenario.vulnerability_type}")
            print(f"   {scenario.description}")
            print()
    
    def select_scenario(self):
        """Select a scenario to work on"""
        
        self.list_scenarios()
        
        try:
            choice = int(input("Select scenario number: ")) - 1
            if 0 <= choice < len(self.scenarios):
                self.current_scenario = self.scenarios[choice]
                print(f"\n✅ Selected: {self.current_scenario.name}")
                self.show_scenario_details()
            else:
                print("Invalid scenario number.")
        except ValueError:
            print("Please enter a valid number.")
    
    def show_scenario_details(self):
        """Show details of current scenario"""
        
        if not self.current_scenario:
            print("No scenario selected.")
            return
        
        scenario = self.current_scenario
        
        print(f"\n🎯 Scenario: {scenario.name}")
        print(f"Vulnerability Type: {scenario.vulnerability_type}")
        print(f"Difficulty: {scenario.difficulty}")
        print(f"\nDescription: {scenario.description}")
        
        print("\n📋 Learning Objectives:")
        for i, objective in enumerate(scenario.objectives, 1):
            print(f"  {i}. {objective}")
        
        print(f"\n💡 Hints Available: {len(scenario.hints)}")
        print("📝 Code Examples Available: Vulnerable vs Secure")
        print("🧪 Test Payloads Available for Testing")
    
    def run_current_scenario(self):
        """Run the current scenario"""
        
        if not self.current_scenario:
            print("Please select a scenario first.")
            return
        
        scenario = self.current_scenario
        
        print(f"\n🚀 Running Scenario: {scenario.name}")
        print("=" * 50)
        print("Commands: 'hint' for hints, 'code' for examples, 'test' for payloads, 'quit' to exit")
        print()
        
        hint_count = 0
        test_count = 0
        
        while True:
            user_input = input("Enter your test input (or command): ").strip()
            
            if user_input.lower() == 'quit':
                break
            elif user_input.lower() == 'hint':
                if hint_count < len(scenario.hints):
                    print(f"💡 Hint {hint_count + 1}: {scenario.hints[hint_count]}")
                    hint_count += 1
                else:
                    print("No more hints available.")
                continue
            elif user_input.lower() == 'code':
                self.show_code_examples(scenario)
                continue
            elif user_input.lower() == 'test':
                self.show_test_payloads(scenario)
                continue
            
            # Test the input with vulnerable system
            print("\n🔴 VULNERABLE System Response:")
            vulnerable_result = self.vulnerable_system.process_request(
                user_input, 
                self.get_context_for_scenario(scenario)
            )
            print(f"LLM Output: {vulnerable_result['llm_response']}")
            print(f"Processed Output: {vulnerable_result['processed_output']}")
            
            # Analyze for vulnerabilities
            vulnerabilities = self.analyze_output_security(vulnerable_result)
            if vulnerabilities:
                print(f"🚨 VULNERABILITIES DETECTED: {', '.join(vulnerabilities)}")
            
            # Test with secure system for comparison
            print("\n🟢 SECURE System Response:")
            secure_result = self.secure_system.process_request(
                user_input,
                self.get_context_for_scenario(scenario)
            )
            print(f"Processed Output: {secure_result['processed_output']}")
            
            test_count += 1
            
            # Check if learning objectives are met
            if self.check_learning_objectives(scenario, vulnerabilities, test_count):
                print("\n🎉 Congratulations! You've completed this scenario!")
                self.user_progress[scenario.name] = {
                    'completed': True,
                    'tests_performed': test_count,
                    'hints_used': hint_count,
                    'timestamp': time.time()
                }
                break
            
            print()
    
    def show_code_examples(self, scenario: SecurityScenario):
        """Show vulnerable and secure code examples"""
        
        print("\n📝 Code Examples:")
        print("-" * 20)
        
        print("🔴 VULNERABLE CODE:")
        print(scenario.vulnerable_code)
        
        print("\n🟢 SECURE CODE:")
        print(scenario.secure_code)
        print()
    
    def show_test_payloads(self, scenario: SecurityScenario):
        """Show test payloads for the scenario"""
        
        print("\n🧪 Test Payloads:")
        print("-" * 15)
        
        for i, payload in enumerate(scenario.test_payloads, 1):
            print(f"{i}. {payload}")
        
        print("\nTry these payloads to see how they affect the output!")
        print()
    
    def get_context_for_scenario(self, scenario: SecurityScenario) -> str:
        """Get appropriate context for scenario testing"""
        
        context_map = {
            "XSS": "html",
            "SQL_INJECTION": "sql",
            "COMMAND_INJECTION": "command",
            "SSRF": "url",
            "PATH_TRAVERSAL": "file"
        }
        
        return context_map.get(scenario.vulnerability_type, "html")
    
    def analyze_output_security(self, result: Dict[str, Any]) -> List[str]:
        """Analyze output for security vulnerabilities"""
        
        vulnerabilities = []
        output = result['processed_output']
        
        # XSS detection
        if re.search(r'<script[^>]*>.*?</script>', output, re.IGNORECASE | re.DOTALL):
            vulnerabilities.append("XSS - Script Tag")
        
        if 'javascript:' in output.lower():
            vulnerabilities.append("XSS - JavaScript Protocol")
        
        if re.search(r'on\w+\s*=', output):
            vulnerabilities.append("XSS - Event Handler")
        
        # SQL Injection detection
        if re.search(r'(union\s+select|drop\s+table|delete\s+from)', output, re.IGNORECASE):
            vulnerabilities.append("SQL Injection")
        
        # Command Injection detection
        if re.search(r'(;\s*(rm|del|cat)|`[^`]*`|\$\([^)]*\))', output):
            vulnerabilities.append("Command Injection")
        
        # SSRF detection
        if re.search(r'(127\.0\.0\.1|localhost|169\.254\.169\.254)', output):
            vulnerabilities.append("SSRF - Internal Network")
        
        # Path Traversal detection
        if re.search(r'\.\.[\\/].*\.\.[\\/]', output):
            vulnerabilities.append("Path Traversal")
        
        # Information Disclosure
        if re.search(r'(api[_\s]?key|password)\s*[:=]\s*[^\s]+', output, re.IGNORECASE):
            vulnerabilities.append("Information Disclosure")
        
        return vulnerabilities
    
    def check_learning_objectives(self, scenario: SecurityScenario, vulnerabilities: List[str], test_count: int) -> bool:
        """Check if learning objectives are met"""
        
        # Basic completion criteria
        if test_count >= 3 and vulnerabilities:
            # Check if the right type of vulnerability was found
            vuln_type_map = {
                "XSS": ["XSS"],
                "SQL_INJECTION": ["SQL Injection"],
                "COMMAND_INJECTION": ["Command Injection"],
                "SSRF": ["SSRF"],
                "PATH_TRAVERSAL": ["Path Traversal"]
            }
            
            expected_vulns = vuln_type_map.get(scenario.vulnerability_type, [])
            found_expected = any(
                any(expected in vuln for expected in expected_vulns)
                for vuln in vulnerabilities
            )
            
            return found_expected
        
        return False
    
    def compare_security_levels(self):
        """Compare different security levels"""
        
        print("\n🔍 Security Level Comparison")
        print("=" * 30)
        
        test_input = input("Enter test input: ").strip()
        context = input("Enter context (html/sql/command/url): ").strip() or "html"
        
        # Test with different security levels
        systems = {
            "Vulnerable": VulnerableLLMSystem("vulnerable"),
            "Partially Secure": VulnerableLLMSystem("partially_secure"),
            "Secure": VulnerableLLMSystem("secure")
        }
        
        for level_name, system in systems.items():
            print(f"\n{level_name} System:")
            result = system.process_request(test_input, context)
            print(f"Output: {result['processed_output']}")
            
            vulnerabilities = self.analyze_output_security(result)
            if vulnerabilities:
                print(f"🚨 Vulnerabilities: {', '.join(vulnerabilities)}")
            else:
                print("✅ No vulnerabilities detected")
    
    def show_progress(self):
        """Show user progress"""
        
        print("\n📊 Your Progress:")
        print("-" * 20)
        
        completed = len(self.user_progress)
        total = len(self.scenarios)
        
        print(f"Completed Scenarios: {completed}/{total}")
        print(f"Progress: {completed/total*100:.1f}%")
        print()
        
        if self.user_progress:
            print("Completed Scenarios:")
            for scenario_name, progress in self.user_progress.items():
                print(f"✅ {scenario_name}")
                print(f"   Tests: {progress['tests_performed']}, Hints: {progress['hints_used']}")
        else:
            print("No scenarios completed yet. Start with XSS basics!")
    
    def show_learning_resources(self):
        """Show learning resources"""
        
        print("\n📖 Learning Resources:")
        print("-" * 25)
        
        resources = [
            {
                'title': 'OWASP Top 10 Web Application Security Risks',
                'description': 'Comprehensive guide to web application vulnerabilities',
                'url': 'https://owasp.org/www-project-top-ten/'
            },
            {
                'title': 'OWASP XSS Prevention Cheat Sheet',
                'description': 'Best practices for preventing XSS attacks',
                'url': 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html'
            },
            {
                'title': 'SQL Injection Prevention',
                'description': 'Techniques for preventing SQL injection attacks',
                'url': 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html'
            },
            {
                'title': 'Command Injection Prevention',
                'description': 'Secure coding practices for command execution',
                'url': 'https://cheatsheetseries.owasp.org/cheatsheets/OS_Command_Injection_Defense_Cheat_Sheet.html'
            }
        ]
        
        for i, resource in enumerate(resources, 1):
            print(f"{i}. {resource['title']}")
            print(f"   {resource['description']}")
            print(f"   URL: {resource['url']}")
            print()
        
        print("💡 Remember: Always use this knowledge for defensive purposes!")

def main():
    """Main function to start the lab"""
    
    lab = OutputSecurityLab()
    lab.start_lab()

if __name__ == "__main__":
    main()